# Generated by Django 4.2.1 on 2023-07-30 02:31

from django.db import migrations, models
import profiles.profileuploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.profileuploadfiles.profile_upload_image_path, verbose_name='Cover Image'),
        ),
    ]
