# Generated by Django 4.2.1 on 2025-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_socialmedia_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('YOUTUBE', 'Youtube'), ('PODCAST', 'Podcast'), ('SPOTIFY', 'Spotify')], max_length=50),
        ),
    ]
