# Generated by Django 4.2.1 on 2023-07-28 20:10

from django.db import migrations, models
import homeevents.homeeventsuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description_1', models.TextField(max_length=1024, verbose_name='Description 1')),
                ('description_2', models.TextField(max_length=1024, verbose_name='Description 2')),
                ('date', models.CharField(max_length=255, verbose_name='Date details')),
                ('time', models.CharField(max_length=255, verbose_name='Time details ')),
                ('location', models.CharField(max_length=255, verbose_name='Location details ')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Cover image')),
                ('home_display', models.BooleanField(default=False, verbose_name='Show In home')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', 'home_display', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='HomeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('events', models.ManyToManyField(to='homeevents.event')),
            ],
            options={
                'verbose_name': 'Home Event',
                'verbose_name_plural': 'Home Events',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
