# Generated by Django 4.2.1 on 2023-07-30 02:31

from django.db import migrations, models
import homeevents.homeeventsuploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('homeevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='homeevent',
            name='title',
            field=models.CharField(default='Home Events', max_length=255, verbose_name='Title'),
        ),
    ]
