# Generated by Django 4.2.1 on 2023-07-30 02:36

from django.db import migrations, models
import homeevents.homeeventsuploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('homeevents', '0002_event_background_image_path_alter_homeevent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='background_image_path',
        ),
        migrations.AddField(
            model_name='homeevent',
            name='background_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Background image'),
        ),
    ]
