# Generated by Django 4.2.1 on 2025-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeevents', '0005_alter_event_description_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_1',
            field=models.TextField(max_length=1024, verbose_name='First Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_2',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Second Description'),
        ),
    ]
