# Generated by Django 4.2.1 on 2023-12-15 11:19

from django.db import migrations, models
import homeevents.homeeventsuploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('homeevents', '0006_alter_event_description_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery_image_path_1',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Gallery image 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image_path_2',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Gallery image 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image_path_3',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Gallery image 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image_path_4',
            field=models.ImageField(blank=True, null=True, upload_to=homeevents.homeeventsuploadfiles.home_events_upload_image_path, verbose_name='Gallery image 4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_2',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Description 2'),
        ),
    ]
