# Generated by Django 4.2.1 on 2023-07-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipinstitute', '0002_alter_leadershipinstitute_title_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='videos',
            field=models.ManyToManyField(blank=True, to='leadershipinstitute.video'),
        ),
    ]
