# Generated by Django 4.2.1 on 2023-07-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipinstitute', '0003_alter_material_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='assesments',
            field=models.ManyToManyField(blank=True, null=True, to='leadershipinstitute.assesment'),
        ),
        migrations.AlterField(
            model_name='material',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, to='leadershipinstitute.assignment'),
        ),
        migrations.AlterField(
            model_name='material',
            name='readings',
            field=models.ManyToManyField(blank=True, null=True, to='leadershipinstitute.reading'),
        ),
        migrations.AlterField(
            model_name='material',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='leadershipinstitute.video'),
        ),
    ]
