# Generated by Django 4.2.1 on 2023-07-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipinstitute', '0004_alter_material_assesments_alter_material_assignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Description'),
        ),
    ]
