# Generated by Django 4.2.1 on 2023-08-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipinstitute', '0008_remove_course_students_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='leadershipinstitute.student'),
        ),
    ]
