# Generated by Django 4.2.1 on 2025-07-31 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0002_alter_powerliving_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, max_length=1024, verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='monthlypowerliving',
            name='articles',
            field=models.ManyToManyField(to='powerliving.article'),
        ),
    ]
