# Generated by Django 4.2.1 on 2025-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0003_article_monthlypowerliving_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
