# Generated by Django 4.2.1 on 2025-08-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quotation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quotation'),
        ),
    ]
