# Generated by Django 4.2.1 on 2025-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0006_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='confession',
            field=models.TextField(blank=True, verbose_name='Confession'),
        ),
        migrations.AddField(
            model_name='article',
            name='prayer_point',
            field=models.TextField(blank=True, verbose_name='Prayer Points'),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scripture References'),
        ),
    ]
