# Generated by Django 4.2.1 on 2025-08-02 12:53

from django.db import migrations, models
import powerliving.powerlivinguploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0007_article_confession_article_prayer_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=powerliving.powerlivinguploadfiles.power_living_upload_image_path, verbose_name='Cover image'),
        ),
    ]
