# Generated by Django 4.2.1 on 2025-08-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerliving', '0008_article_cover_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypowerliving',
            name='articles',
            field=models.ManyToManyField(blank=True, to='powerliving.article'),
        ),
    ]
