# Generated by Django 4.2.1 on 2023-07-28 20:10

from django.db import migrations, models
import home.homeuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_logo_image_path', models.ImageField(blank=True, null=True, upload_to=home.homeuploadfiles.home_upload_image_path, verbose_name='Top logo image')),
                ('footer_address', models.CharField(max_length=255, verbose_name='Footer Address')),
                ('footer_phone', models.CharField(max_length=255, verbose_name='Footer Phone')),
                ('footer_email', models.CharField(max_length=255, verbose_name='Footer email')),
                ('footer_logo_image_path', models.ImageField(blank=True, null=True, upload_to=home.homeuploadfiles.home_upload_image_path, verbose_name='Footer logo image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Homepage Details',
                'ordering': ('id', 'created_at'),
            },
        ),
    ]
