# Generated by Django 4.2.1 on 2023-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='url',
            field=models.CharField(default='default', max_length=255, verbose_name='Live Event Url'),
        ),
    ]
