# Generated by Django 4.2.1 on 2023-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayercity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayercity',
            name='title',
            field=models.CharField(default='Prayer City', max_length=255, verbose_name='Title'),
        ),
    ]
