# Generated by Django 4.2.1 on 2023-07-28 20:10

from django.db import migrations, models
import quoteoftheday.quoteofthedayuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOfTheDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Intro tile')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Sub tile')),
                ('text', models.TextField(max_length=1024, verbose_name='Quote of the day text')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('icon_image_path', models.ImageField(blank=True, null=True, upload_to=quoteoftheday.quoteofthedayuploadfiles.quote_of_the_day_upload_image_path, verbose_name='Icon image')),
                ('background_icon_image_path', models.ImageField(blank=True, null=True, upload_to=quoteoftheday.quoteofthedayuploadfiles.quote_of_the_day_upload_image_path, verbose_name='Background image')),
                ('quote_date', models.DateField(verbose_name='Quote date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Quote of the day',
                'verbose_name_plural': 'Quotes of the day',
                'ordering': ('title', 'sub_title', 'text', 'created_at'),
            },
        ),
    ]
