# Generated by Django 4.2.1 on 2023-07-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteoftheday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteoftheday',
            options={'ordering': ('title', 'text', 'created_at'), 'verbose_name': 'Quote of the day', 'verbose_name_plural': 'Quotes of the day'},
        ),
        migrations.RemoveField(
            model_name='quoteoftheday',
            name='background_icon_image_path',
        ),
        migrations.RemoveField(
            model_name='quoteoftheday',
            name='icon_image_path',
        ),
        migrations.RemoveField(
            model_name='quoteoftheday',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='quoteoftheday',
            name='quote_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='quoteoftheday',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='quoteoftheday',
            name='title',
            field=models.CharField(default='Quote Of The Day', max_length=255, verbose_name='Title'),
        ),
    ]
