# Generated by Django 4.2.1 on 2023-07-28 20:10

from django.db import migrations, models
import homeslider.homeslidersuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=homeslider.homeslidersuploadfiles.home_sliders_upload_image_path, verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=homeslider.homeslidersuploadfiles.home_sliders_upload_image_path, verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=homeslider.homeslidersuploadfiles.home_sliders_upload_image_path, verbose_name='Image 3')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=homeslider.homeslidersuploadfiles.home_sliders_upload_image_path, verbose_name='Cover Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
                'ordering': ('id', 'description', 'created_at'),
            },
        ),
    ]
