# Generated by Django 4.2.1 on 2023-08-22 09:45

from django.db import migrations, models
import homeministries.homeministriesuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=homeministries.homeministriesuploadfiles.home_ministries_upload_image_path, verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='HomeMinistries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Ministries Material', max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ministries', models.ManyToManyField(to='homeministries.ministries')),
            ],
            options={
                'verbose_name': 'Home Ministry',
                'verbose_name_plural': 'Home Ministries',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
