# Generated by Django 4.2.1 on 2023-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeministries',
            name='title',
            field=models.CharField(default='Ministries', max_length=255, verbose_name='Title'),
        ),
    ]
