# Generated by Django 4.2.1 on 2023-07-28 20:10

from django.db import migrations, models
import homeministriesmaterial.homeministriesmaterialuploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinistriesMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Ministries material title')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=homeministriesmaterial.homeministriesmaterialuploadfiles.home_ministries_material_upload_image_path, verbose_name='Cover image')),
                ('redirect_link', models.CharField(max_length=255, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ('title', 'description', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='HomeMinistriesMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('materials', models.ManyToManyField(to='homeministriesmaterial.ministriesmaterial')),
            ],
            options={
                'verbose_name': 'Home Ministry Material',
                'verbose_name_plural': 'Home Ministries Materials',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
