# Generated by Django 4.2.1 on 2023-08-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeministriesmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministriesmaterial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
