# Generated by Django 4.2.1 on 2023-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeministriesmaterial', '0002_alter_ministriesmaterial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeministriesmaterial',
            name='title',
            field=models.CharField(default='Ministries Material', max_length=255, verbose_name='Title'),
        ),
    ]
